name: Pull Request Test

on: [pull_request, push]

jobs:
  test:
    name: Test on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
  
      - name: Build
        shell: bash
        run: |
          CI/build.sh
      
      - name: Run Core Test
        shell: pwsh
        run: |
          out/build/Release/Release/FBX-glTF-conv-core-test.exe

      - name: Run CLI Test
        shell: pwsh
        run: |
          out/build/Release/Release/FBX-glTF-conv-test.exe

  test_on_mac:
    name: Test on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          CI/build.sh
          ls -l out/install/Release/bin
          ls -l out/install/Release/lib
          lipo -info out/install/Release/bin/libfbxsdk.dylib
          lipo -info out/install/Release/bin/libBeeCore.dylib
          lipo -info out/install/Release/lib/libBeeCore.dylib
          lipo -info out/install/Release/bin/FBX-glTF-conv

          # echo "otool bin/libBeeCore.dylib ..."
          # otool -l out/install/Release/bin/libBeeCore.dylib | grep -A 5 LC_VERSION_MIN_MACOSX
          # echo "otool lib/libBeeCore.dylib ..."
          # otool -l out/install/Release/lib/libBeeCore.dylib | grep -A 5 LC_VERSION_MIN_MACOSX
          # echo "otool bin/FBX-glTF-conv ..."
          # otool -l out/install/Release/bin/FBX-glTF-conv | grep -A 5 LC_VERSION_MIN_MACOSX

      - name: Run CLI Tests
        continue-on-error: true
        run: |
          ls out
          chmod 777 ./out/install/Release/bin/FBX-glTF-conv
          ./out/install/Release/bin/FBX-glTF-conv --help
          
