name: Pull Request Test

on: [pull_request, push]

jobs:
  test:
    name: Test on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
  
      - name: Build
        shell: bash
        run: |
          CI/build.sh
      
      - name: Run Core Test
        shell: pwsh
        run: |
          out/build/Release/Release/FBX-glTF-conv-core-test.exe

      - name: Run CLI Test
        shell: pwsh
        run: |
          out/build/Release/Release/FBX-glTF-conv-test.exe

  test_on_mac:
    name: Test on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          CI/build.sh
          ls -l out/Release/bin
          ls -l out/Release/lib
          find out/Release -name "*.dylib" | xargs lipo -info
          lipo -info out/Release/bin/FBX-glTF-conv

      - name: Run CLI Tests
        run: |
          ls out
          chmod 777 ./out/Release/bin/FBX-glTF-conv
          ./out/Release/bin/FBX-glTF-conv --help
